
DROP TABLE IF EXISTS publicacoes CASCADE;
DROP TABLE IF EXISTS seguidores CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;

CREATE TABLE usuarios (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(50)  NOT NULL,
  nick VARCHAR(50)  NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  senha VARCHAR(100) NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE seguidores (
  usuario_id  INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  seguidor_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  PRIMARY KEY (usuario_id, seguidor_id)
);

CREATE TABLE publicacoes (
  id         SERIAL PRIMARY KEY,
  titulo     VARCHAR(50)  NOT NULL,
  conteudo   VARCHAR(500) NOT NULL,
  autor_id   INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  curtidas   INTEGER      DEFAULT 0,
  criado_em  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
);